# -*- coding: utf-8 -*-
"""严格历史混合检索增强上下文学习配置。"""
import os
import sys


SERVICE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = os.path.dirname(SERVICE_DIR)
STAGE2_DIR = os.path.join(SERVICE_DIR, "阶段2")
sys.path.insert(0, STAGE2_DIR)
import config2 as BASE_CONFIG

SOURCE_SLICE_TAG = "40k"
VAL_SLICE_TAG = "40k"
TOP_K = 4
QUERY_BATCH_SIZE = 512
BANK_CHUNK_SIZE = 40000
RETRIEVAL_DEVICE = "cuda"  # CUDA不可用时自动回退CPU
RETRIEVAL_STRATEGY = "hybrid"  # hybrid / vector / random
HISTORY_MODE = "prior_day"     # 只允许检索更早日期，同日样本排除
VECTOR_RECALL_K = 128           # 历史范围内的向量候选召回数
STRUCT_CANDIDATE_CAP = 256      # 分层结构候选最多保留数
METRIC = "cosine"

# 混合重排权重。z相似度仍是主信号，结构条件用于消除语义相似的模糊候选。
ROUTE_BONUS = 0.08
CARRIER_BONUS = 0.03
ORIGIN_BONUS = 0.02
DESTINATION_BONUS = 0.02
WEEKDAY_BONUS = 0.015
TIME_BONUS = 0.04
WEATHER_BONUS = 0.02
TIME_SCALE_MINUTES = 240.0
WEATHER_SCALE = 3.0

STAGE2_SLICE_DIR = os.path.join(BASE, "data", "阶段2切片")
FUSED_DIR = os.path.join(BASE, "model", "阶段1")
RETRIEVAL_DATA_DIR = os.path.join(
    BASE, "data", "阶段2检索增强", SOURCE_SLICE_TAG, RETRIEVAL_STRATEGY)
RETRIEVAL_MODEL_DIR = os.path.join(BASE, "model", "阶段2", "检索增强")
GEMMA_PATH = BASE_CONFIG.GEMMA_PATH
TAB_CSV = BASE_CONFIG.TAB_CSV
MAX_SAMPLES = BASE_CONFIG.MAX_SAMPLES
USE_PREBUILT_SLICES = BASE_CONFIG.USE_PREBUILT_SLICES
VAL_CAP = BASE_CONFIG.VAL_CAP
TEST_CAP = BASE_CONFIG.TEST_CAP
SEED = BASE_CONFIG.SEED
EPOCHS = BASE_CONFIG.EPOCHS
LR = BASE_CONFIG.LR
BATCH = BASE_CONFIG.BATCH
VAL_STEPS = BASE_CONFIG.VAL_STEPS
PATIENCE = BASE_CONFIG.PATIENCE
LORA_R = BASE_CONFIG.LORA_R
LORA_ALPHA = BASE_CONFIG.LORA_ALPHA
LORA_DROPOUT = BASE_CONFIG.LORA_DROPOUT
TARGET_MODULES = BASE_CONFIG.TARGET_MODULES
USE_POS_WEIGHT = BASE_CONFIG.USE_POS_WEIGHT
SHUFFLE = BASE_CONFIG.SHUFFLE
FULL_PASS_BEFORE_EARLY_STOP = BASE_CONFIG.FULL_PASS_BEFORE_EARLY_STOP

# 检索案例会扩展文本长度；左截断保证当前航班和分类位置始终保留。
MAX_LEN = 192
NUM_SOFT = BASE_CONFIG.NUM_SOFT
PROJ_NORM = BASE_CONFIG.PROJ_NORM
POOL_ATTN = BASE_CONFIG.POOL_ATTN
HEAD_MLP = BASE_CONFIG.HEAD_MLP
TOKEN_GATE = BASE_CONFIG.TOKEN_GATE
Z_SHORTCUT = BASE_CONFIG.Z_SHORTCUT
USE_SCHED = BASE_CONFIG.USE_SCHED
SAVE_PREDICTIONS = True
INCLUDE_SIMILARITY_SCORE = False
RUN_TAG = f"{SOURCE_SLICE_TAG}_top{TOP_K}_严格历史混合检索_末端分类"


def cache_path(split):
    if split not in {"train", "val", "test"}:
        raise ValueError(f"Unsupported split={split}")
    return os.path.join(RETRIEVAL_DATA_DIR, f"{split}_topk.pt")
